### ISSUE TITLE
[Feature] Add code linting/formatting tool

### ISSUE THREAD

**Issue by Aebel-Shajan** [Aebel-Shajan/Wocket-Weague#9]
Add a code formatting/linting tool like eslint or prettiers or maybe biome? Try and stick to the best practices of other typescript three js projects.

Thinking about using pre commit hooks but idk if thats too extra.

**Comment by jaas666** [comment]
Submitted #11 for this issue.

**Comment by Aebel-Shajan** [comment]
Resolve
